// Code generated by protoc-gen-go. DO NOT EDIT.
// source: firmware.proto

package ctl

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FirmwareQueryReq struct {
	QueryScm             bool     `protobuf:"varint,1,opt,name=queryScm,proto3" json:"queryScm,omitempty"`
	QueryNvme            bool     `protobuf:"varint,2,opt,name=queryNvme,proto3" json:"queryNvme,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FirmwareQueryReq) Reset()         { *m = FirmwareQueryReq{} }
func (m *FirmwareQueryReq) String() string { return proto.CompactTextString(m) }
func (*FirmwareQueryReq) ProtoMessage()    {}
func (*FirmwareQueryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_138455e383c002dd, []int{0}
}

func (m *FirmwareQueryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirmwareQueryReq.Unmarshal(m, b)
}
func (m *FirmwareQueryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirmwareQueryReq.Marshal(b, m, deterministic)
}
func (m *FirmwareQueryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirmwareQueryReq.Merge(m, src)
}
func (m *FirmwareQueryReq) XXX_Size() int {
	return xxx_messageInfo_FirmwareQueryReq.Size(m)
}
func (m *FirmwareQueryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FirmwareQueryReq.DiscardUnknown(m)
}

var xxx_messageInfo_FirmwareQueryReq proto.InternalMessageInfo

func (m *FirmwareQueryReq) GetQueryScm() bool {
	if m != nil {
		return m.QueryScm
	}
	return false
}

func (m *FirmwareQueryReq) GetQueryNvme() bool {
	if m != nil {
		return m.QueryNvme
	}
	return false
}

type ScmFirmwareQueryResp struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Handle               uint32   `protobuf:"varint,2,opt,name=handle,proto3" json:"handle,omitempty"`
	ActiveVersion        string   `protobuf:"bytes,3,opt,name=activeVersion,proto3" json:"activeVersion,omitempty"`
	StagedVersion        string   `protobuf:"bytes,4,opt,name=stagedVersion,proto3" json:"stagedVersion,omitempty"`
	ImageMaxSizeBytes    uint32   `protobuf:"varint,5,opt,name=imageMaxSizeBytes,proto3" json:"imageMaxSizeBytes,omitempty"`
	UpdateStatus         uint32   `protobuf:"varint,6,opt,name=updateStatus,proto3" json:"updateStatus,omitempty"`
	Error                string   `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScmFirmwareQueryResp) Reset()         { *m = ScmFirmwareQueryResp{} }
func (m *ScmFirmwareQueryResp) String() string { return proto.CompactTextString(m) }
func (*ScmFirmwareQueryResp) ProtoMessage()    {}
func (*ScmFirmwareQueryResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_138455e383c002dd, []int{1}
}

func (m *ScmFirmwareQueryResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScmFirmwareQueryResp.Unmarshal(m, b)
}
func (m *ScmFirmwareQueryResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScmFirmwareQueryResp.Marshal(b, m, deterministic)
}
func (m *ScmFirmwareQueryResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScmFirmwareQueryResp.Merge(m, src)
}
func (m *ScmFirmwareQueryResp) XXX_Size() int {
	return xxx_messageInfo_ScmFirmwareQueryResp.Size(m)
}
func (m *ScmFirmwareQueryResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ScmFirmwareQueryResp.DiscardUnknown(m)
}

var xxx_messageInfo_ScmFirmwareQueryResp proto.InternalMessageInfo

func (m *ScmFirmwareQueryResp) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ScmFirmwareQueryResp) GetHandle() uint32 {
	if m != nil {
		return m.Handle
	}
	return 0
}

func (m *ScmFirmwareQueryResp) GetActiveVersion() string {
	if m != nil {
		return m.ActiveVersion
	}
	return ""
}

func (m *ScmFirmwareQueryResp) GetStagedVersion() string {
	if m != nil {
		return m.StagedVersion
	}
	return ""
}

func (m *ScmFirmwareQueryResp) GetImageMaxSizeBytes() uint32 {
	if m != nil {
		return m.ImageMaxSizeBytes
	}
	return 0
}

func (m *ScmFirmwareQueryResp) GetUpdateStatus() uint32 {
	if m != nil {
		return m.UpdateStatus
	}
	return 0
}

func (m *ScmFirmwareQueryResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type FirmwareQueryResp struct {
	ScmResults           []*ScmFirmwareQueryResp `protobuf:"bytes,1,rep,name=scmResults,proto3" json:"scmResults,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *FirmwareQueryResp) Reset()         { *m = FirmwareQueryResp{} }
func (m *FirmwareQueryResp) String() string { return proto.CompactTextString(m) }
func (*FirmwareQueryResp) ProtoMessage()    {}
func (*FirmwareQueryResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_138455e383c002dd, []int{2}
}

func (m *FirmwareQueryResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirmwareQueryResp.Unmarshal(m, b)
}
func (m *FirmwareQueryResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirmwareQueryResp.Marshal(b, m, deterministic)
}
func (m *FirmwareQueryResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirmwareQueryResp.Merge(m, src)
}
func (m *FirmwareQueryResp) XXX_Size() int {
	return xxx_messageInfo_FirmwareQueryResp.Size(m)
}
func (m *FirmwareQueryResp) XXX_DiscardUnknown() {
	xxx_messageInfo_FirmwareQueryResp.DiscardUnknown(m)
}

var xxx_messageInfo_FirmwareQueryResp proto.InternalMessageInfo

func (m *FirmwareQueryResp) GetScmResults() []*ScmFirmwareQueryResp {
	if m != nil {
		return m.ScmResults
	}
	return nil
}

func init() {
	proto.RegisterType((*FirmwareQueryReq)(nil), "ctl.FirmwareQueryReq")
	proto.RegisterType((*ScmFirmwareQueryResp)(nil), "ctl.ScmFirmwareQueryResp")
	proto.RegisterType((*FirmwareQueryResp)(nil), "ctl.FirmwareQueryResp")
}

func init() {
	proto.RegisterFile("firmware.proto", fileDescriptor_138455e383c002dd)
}

var fileDescriptor_138455e383c002dd = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xbf, 0x4e, 0xf3, 0x30,
	0x14, 0xc5, 0x95, 0x2f, 0x5f, 0x43, 0x7b, 0xa1, 0xa8, 0xb5, 0x2a, 0x64, 0x10, 0x43, 0x15, 0x31,
	0x74, 0x40, 0x19, 0x60, 0x62, 0x65, 0x60, 0x82, 0x4a, 0x38, 0x12, 0xbb, 0x71, 0x2e, 0xc5, 0x52,
	0xdc, 0xa4, 0xf6, 0x75, 0xa1, 0x3c, 0x37, 0x0f, 0x80, 0xe2, 0x94, 0x3f, 0xa1, 0x6c, 0xe7, 0x9c,
	0xfb, 0xf3, 0xb9, 0xb2, 0x0d, 0x87, 0x4f, 0xda, 0x9a, 0x17, 0x69, 0x31, 0xab, 0x6d, 0x45, 0x15,
	0x8b, 0x15, 0x95, 0xe9, 0x2d, 0x8c, 0x6e, 0xb6, 0xf1, 0xbd, 0x47, 0xbb, 0x11, 0xb8, 0x62, 0x27,
	0xd0, 0x5f, 0x35, 0x3a, 0x57, 0x86, 0x47, 0xd3, 0x68, 0xd6, 0x17, 0x5f, 0x9e, 0x9d, 0xc2, 0x20,
	0xe8, 0xf9, 0xda, 0x20, 0xff, 0x17, 0x86, 0xdf, 0x41, 0xfa, 0x1e, 0xc1, 0x24, 0x57, 0xe6, 0x57,
	0xa3, 0xab, 0xd9, 0x08, 0x62, 0xaf, 0x8b, 0xd0, 0x36, 0x10, 0x8d, 0x64, 0x47, 0x90, 0x3c, 0xcb,
	0x65, 0x51, 0xb6, 0x2d, 0x43, 0xb1, 0x75, 0xec, 0x0c, 0x86, 0x52, 0x91, 0x5e, 0xe3, 0x03, 0x5a,
	0xa7, 0xab, 0x25, 0x8f, 0xc3, 0x99, 0x6e, 0xd8, 0x50, 0x8e, 0xe4, 0x02, 0x8b, 0x4f, 0xea, 0x7f,
	0x4b, 0x75, 0x42, 0x76, 0x0e, 0x63, 0x6d, 0xe4, 0x02, 0xef, 0xe4, 0x6b, 0xae, 0xdf, 0xf0, 0x7a,
	0x43, 0xe8, 0x78, 0x2f, 0xac, 0xdb, 0x1d, 0xb0, 0x14, 0x0e, 0x7c, 0x5d, 0x48, 0xc2, 0x9c, 0x24,
	0x79, 0xc7, 0x93, 0x00, 0x76, 0x32, 0x36, 0x81, 0x1e, 0x5a, 0x5b, 0x59, 0xbe, 0x17, 0xf6, 0xb5,
	0x26, 0x9d, 0xc3, 0x78, 0xf7, 0xca, 0x57, 0x00, 0x4e, 0x19, 0x81, 0xce, 0x97, 0xe4, 0x78, 0x34,
	0x8d, 0x67, 0xfb, 0x17, 0xc7, 0x99, 0xa2, 0x32, 0xfb, 0xeb, 0x85, 0xc4, 0x0f, 0xf8, 0x31, 0x09,
	0x1f, 0x74, 0xf9, 0x11, 0x00, 0x00, 0xff, 0xff, 0xd4, 0xc6, 0xe4, 0xfe, 0xb2, 0x01, 0x00, 0x00,
}
